language: clojure
jdk:
- oraclejdk8
script:
- lein do clean, compile, check, eastwood
# HACK: download the file before the test starts
- wget -O ./resources/test/frankfurt-am-main.edn.gz ${FRANKFURT_AREA_EDN}
- if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
    lein trampoline test :benchmark;
  else
    lein trampoline test;
  fi

deploy:
# deploy to clojars
- provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    branch: master
    tags: true
# deploy the jar directly to github
- provider: releases
  file_glob: true
  file: target/kamal*.jar
  skip_cleanup: true
  on:
    branch: master
    tags: true
