language: clojure
jdk:
- oraclejdk8

stages:
- smoke
- test
#- benchmark

jobs:
  include:
  - stage: smoke
    script: lein do clean, compile, check, eastwood
  - stage: test
    script: lein trampoline test
  #- stage: test
  #    script: lein trampoline test :benchmark

deploy:
# deploy to clojars
- provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    branch: master
    tags: true
# deploy the jar directly to github
- provider: releases
  file_glob: true
  file: target/kamal*.jar
  skip_cleanup: true
  on:
    branch: master
    tags: true
