language: clojure
jdk:
- oraclejdk8

jobs:
  include:
  - stage: Generative Tests
    script: lein do clean, compile, check, eastwood, test
  - stage: Integration Tests
    script:
    - wget -O ./resources/test/frankfurt-am-main.edn.gz ${FRANKFURT_AREA_EDN}
    - lein trampoline test :integration

  - stage: Benchmark
    if: type = cron
    script:
      - wget -O ./resources/test/frankfurt-am-main.edn.gz ${FRANKFURT_AREA_EDN}
      - lein trampoline test :benchmark

  - stage: Release
    script: echo "Deploying to GitHub releases ..."
    if: tag IS present
    deploy:
      provider: releases
      file_glob: true
      file: target/kamal*.jar
      skip_cleanup: true
      on:
        tags: true
  - stage: Release
    script: echo "Deploying to Clojars ..."
    if: tag IS present
    deploy:
      provider: script
      script: lein deploy
      skip_cleanup: true
      on:
        tags: true
