language: clojure
jdk:
- oraclejdk8
before_script:
  - env
  - wget --verbose -O ./resources/test/frankfurt-am-main.edn.gz ${FRANKFURT_AREA_EDN}
script:
- lein do clean, compile, check, eastwood
# HACK: download the file before the test starts
- lein trampoline test
deploy:
- provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    branch: master
    tags: true
- provider: releases
  file_glob: true
  file: target/kamal*.jar
  skip_cleanup: true
  on:
    branch: master
    tags: true
