language: clojure
jdk:
- oraclejdk8
script:
- lein do clean, compile, check, eastwood
- env
# HACK: download the file before the test starts
- lein trampoline test
deploy:
- provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    branch: master
    tags: true
# deploy the jar directly to github
- provider: releases
  file_glob: true
  file: target/kamal*.jar
  skip_cleanup: true
  on:
    branch: master
    tags: true
