
language: clojure
jdk:
  - oraclejdk8
# check that it compiles && run linters && run tests
# stop if any of them fails
#script: lein do clean, compile, check, eastwood '{:exclude-namespaces [hiposfer.service.conjectures.specs]}', test
script:
  - lein clean
  - lein compile
  - lein check
  - lein eastwood '{:exclude-namespaces [hiposfer.service.routing.graph.specs hiposfer.service.routing.spec]}'
  - lein test
#TODO: slack notification
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
