steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - app
  - deploy
  - --quiet
  - --image-url=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
